import { primitivesFrom, requirePrimitive } from "../../../core/primitives.js";
import { buildBackendDevelop } from "../domains/backend.js";
import { buildFrontendDevelop } from "../domains/frontend.js";
import { buildNextjsAppDevelop } from "../domains/nextjs_app.js";
import { buildReactNativeAppDevelop } from "../domains/react_native_app.js";
import { buildSdkDevelop } from "../domains/sdk.js";
import { buildInfraDevelop } from "../domains/infra.js";
import { buildAwsServerlessDevelop } from "../domains/aws_serverless.js";
import { buildAwsDynamodbDevelop } from "../domains/aws_dynamodb.js";
import { buildKubernetesServiceDevelop } from "../domains/kubernetes_service.js";
import { buildGcpCloudRunDevelop } from "../domains/gcp_cloudrun.js";
import { buildPostgresDbDevelop } from "../domains/postgres_db.js";
import { buildRedisCacheDevelop } from "../domains/redis_cache.js";
import { buildEventStreamingDevelop } from "../domains/event_streaming.js";
import { buildFastapiServiceDevelop } from "../domains/fastapi_service.js";
import { buildGraphqlApiDevelop } from "../domains/graphql_api.js";
import { buildGrpcServiceDevelop } from "../domains/grpc_service.js";
import { buildRailsAppDevelop } from "../domains/rails_app.js";
import { buildDjangoAppDevelop } from "../domains/django_app.js";
import { buildSpringBootServiceDevelop } from "../domains/spring_boot_service.js";
import { buildDotnetWebapiDevelop } from "../domains/dotnet_webapi.js";
import { buildTerraformModuleDevelop } from "../domains/terraform_module.js";
import { buildHelmChartDevelop } from "../domains/helm_chart.js";
import { buildAzureFunctionsDevelop } from "../domains/azure_functions.js";
import { buildStripeIntegrationDevelop } from "../domains/stripe_integration.js";
import { buildDataDevelop } from "../domains/data.js";
import { buildWorkersDevelop } from "../domains/workers.js";
import { buildIntegrationDevelop } from "../domains/integration.js";
import { buildPackageDevelop } from "../domains/package.js";

export const buildDevelopForDomain = (domain, opts = {}) => {
  const normalized = String(domain ?? "backend").toLowerCase();
  if (normalized === "frontend") return buildFrontendDevelop(opts);
  if (normalized === "nextjs_app" || normalized === "nextjs" || normalized === "next") return buildNextjsAppDevelop(opts);
  if (normalized === "react_native_app" || normalized === "reactnative" || normalized === "rn") return buildReactNativeAppDevelop(opts);
  if (normalized === "sdk") return buildSdkDevelop(opts);
  if (normalized === "infra" || normalized === "infrastructure") return buildInfraDevelop(opts);
  if (normalized === "aws_serverless" || normalized === "aws") return buildAwsServerlessDevelop(opts);
  if (normalized === "aws_dynamodb" || normalized === "dynamodb" || normalized === "ddb") return buildAwsDynamodbDevelop(opts);
  if (normalized === "kubernetes_service" || normalized === "k8s" || normalized === "kubernetes") return buildKubernetesServiceDevelop(opts);
  if (normalized === "gcp_cloudrun" || normalized === "gcp" || normalized === "cloudrun") return buildGcpCloudRunDevelop(opts);
  if (normalized === "postgres_db" || normalized === "postgresql" || normalized === "postgres") return buildPostgresDbDevelop(opts);
  if (normalized === "redis_cache" || normalized === "redis") return buildRedisCacheDevelop(opts);
  if (normalized === "event_streaming" || normalized === "kafka" || normalized === "events" || normalized === "streaming") return buildEventStreamingDevelop(opts);
  if (normalized === "fastapi_service" || normalized === "fastapi") return buildFastapiServiceDevelop(opts);
  if (normalized === "graphql_api" || normalized === "graphql") return buildGraphqlApiDevelop(opts);
  if (normalized === "grpc_service" || normalized === "grpc") return buildGrpcServiceDevelop(opts);
  if (normalized === "rails_app" || normalized === "rails" || normalized === "ruby_on_rails") return buildRailsAppDevelop(opts);
  if (normalized === "django_app" || normalized === "django") return buildDjangoAppDevelop(opts);
  if (normalized === "spring_boot_service" || normalized === "spring" || normalized === "springboot") return buildSpringBootServiceDevelop(opts);
  if (normalized === "dotnet_webapi" || normalized === "dotnet" || normalized === "aspnet") return buildDotnetWebapiDevelop(opts);
  if (normalized === "terraform_module" || normalized === "terraform" || normalized === "tf") return buildTerraformModuleDevelop(opts);
  if (normalized === "helm_chart" || normalized === "helm") return buildHelmChartDevelop(opts);
  if (normalized === "azure_functions" || normalized === "azure" || normalized === "functions") return buildAzureFunctionsDevelop(opts);
  if (normalized === "stripe_integration" || normalized === "stripe") return buildStripeIntegrationDevelop(opts);
  if (normalized === "data") return buildDataDevelop(opts);
  if (normalized === "workers") return buildWorkersDevelop(opts);
  if (normalized === "integration") return buildIntegrationDevelop(opts);
  if (normalized === "package") return buildPackageDevelop(opts);
  return buildBackendDevelop(opts);
};

export const requireAct = (ctx = {}) => {
  const { act } = primitivesFrom(ctx);
  return requirePrimitive("act", act);
};
