export const domainAliases = {
  ui: "frontend",
  fe: "frontend",
  be: "backend",
  infrastructure: "infra",
  platform: "infra",
  worker: "workers",
  jobs: "workers",
  pkg: "package",
  next: "nextjs_app",
  nextjs: "nextjs_app",
  rn: "react_native_app",
  reactnative: "react_native_app",
  aws: "aws_serverless",
  dynamodb: "aws_dynamodb",
  ddb: "aws_dynamodb",
  k8s: "kubernetes_service",
  kubernetes: "kubernetes_service",
  cloudrun: "gcp_cloudrun",
  gcp: "gcp_cloudrun",
  postgres: "postgres_db",
  postgresql: "postgres_db",
  redis: "redis_cache",
  kafka: "event_streaming",
  streaming: "event_streaming",
  events: "event_streaming",
  fastapi: "fastapi_service",
  graphql: "graphql_api",
  grpc: "grpc_service",
  rails: "rails_app",
  ruby_on_rails: "rails_app",
  django: "django_app",
  spring: "spring_boot_service",
  springboot: "spring_boot_service",
  dotnet: "dotnet_webapi",
  aspnet: "dotnet_webapi",
  terraform: "terraform_module",
  tf: "terraform_module",
  helm: "helm_chart",
  functions: "azure_functions",
  azure: "azure_functions",
  stripe: "stripe_integration",
  express: "express_service",
  node: "express_service",
  nodejs: "express_service",
  nestjs: "nestjs_service",
  flask: "flask_service",
  golang: "go_service",
  go: "go_service",
  rust: "rust_service",
  vue: "vue_app",
  vuejs: "vue_app",
  svelte: "sveltekit_app",
  sveltekit: "sveltekit_app",
  angular: "angular_app",
  flutter: "flutter_app",
  dart: "flutter_app",
  s3: "aws_s3",
  aws_s3: "aws_s3",
  sqs: "aws_sqs",
  aws_sqs: "aws_sqs",
  eventbridge: "aws_eventbridge",
  rds: "aws_rds_postgres",
  rds_postgres: "aws_rds_postgres",
  aws_rds: "aws_rds_postgres",
  pubsub: "gcp_pubsub",
  gcp_pubsub: "gcp_pubsub",
  firestore: "gcp_firestore",
  cosmos: "azure_cosmosdb",
  cosmosdb: "azure_cosmosdb",
  servicebus: "azure_servicebus",
  cli: "cli_tool",
};

export const normalizeDomainName = (domain, fallback = "backend") => {
  const raw = domain == null ? fallback : domain;
  const normalized = String(raw).toLowerCase().trim();
  if (!normalized) return fallback;
  return domainAliases[normalized] ?? normalized;
};

